plugins = []
headers = []
redirects = []

[functions]

  [functions."*"]

[build]
publish = "C:\\Users\\IT\\OneDrive - DrugStoc\\MARKETING\\E-COMMERCE\\E-COMMERCE"
publishOrigin = "default"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]